name: Shop
version: 1.0
main: dev.shop.ShopPlugin
api-version: 1.21
author: YourName
description: 経済とショップ機能を追加するプラグイン

commands:
  sell:
    description: 手に持っているアイテムを売却します
    usage: /sell
  selllist:
    description: 売却可能なアイテム一覧を表示します
    usage: /selllist
  money:
    description: 自分の所持金を確認します
    usage: /money
  shophelp:
    description: プラグインの概要説明を表示します
    usage: /shophelp
  shopcommandlist:
    description: コマンド一覧を表示します
    usage: /shopcommandlist
  officialshop:
    description: 公式ショップを開きます
    usage: /officialshop
  blacklistin:
    description: ブラックリストにプレイヤーを追加します
    usage: /blacklistin <player>
  blacklistout:
    description: ブラックリストからプレイヤーを削除します
    usage: /blacklistout <player>
